DELETE FROM exp_churches;
INSERT INTO exp_churches (name) SELECT name FROM GoogleMap ORDER BY name;
UPDATE exp_churches SET place = (SELECT place FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET date = (SELECT TRIM(REPLACE(SUBSTR(body, INSTR(body, '- Date:'), INSTR(body, char(10))-1), '- Date:', '')) FROM notes n WHERE n.title = exp_churches.name);
UPDATE exp_churches SET dedication = (SELECT dedication1 || COALESCE (' and ' || dedication2, '') FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET diocese = (SELECT diocese FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET grade = (SELECT grade FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET dedication1 = (SELECT dedication1 FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET dedication2 = (SELECT dedication2 FROM GoogleMap g WHERE g.name = exp_churches.name);
UPDATE exp_churches SET notes = (SELECT TRIM(REPLACE(SUBSTR(SUBSTR(body, INSTR(body, '## Details')), 1, INSTR(SUBSTR(body, INSTR(body, '## Details')), '* * *')-1), '## Details', ''), char(10)) FROM notes n WHERE n.title = exp_churches.name);
UPDATE exp_churches SET photo = (SELECT SUBSTR(OrigName, 1, INSTR(OrigName, '.')) || 'jpg' FROM Photo p WHERE p.Church = exp_churches.name);
UPDATE exp_churches SET subimages_id = (SELECT ID FROM Photo p WHERE p.Church = exp_churches.name);
UPDATE exp_churches SET note_id = (SELECT id FROM notes n WHERE n.title = exp_churches.name);
UPDATE exp_churches SET status_no_inside_photo = 0;
UPDATE exp_churches SET status_no_inside_photo = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'revisit status: seen inside but no photos'));
UPDATE exp_churches SET category = (SELECT 'Church' FROM Photo p WHERE p.Church = exp_churches.name);
UPDATE exp_churches SET status_visited = 0;
UPDATE exp_churches SET status_visited = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'status: visited'));
UPDATE exp_churches SET status_not_been_inside = 0;
UPDATE exp_churches SET status_not_been_inside = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'revisit status: need to revisit for inside'));
UPDATE exp_churches SET status_not_been_inside_and_revisit_not_planned = 0;
UPDATE exp_churches SET status_not_been_inside_and_revisit_not_planned = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'revisit status: not planned to revisit'));
UPDATE exp_churches SET status_visit_planned = 0;
UPDATE exp_churches SET status_visit_planned = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'status: planned to visit'));
UPDATE exp_churches SET status_visit_planned_priority = 0;
UPDATE exp_churches SET status_visit_planned_priority = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'status: planned to visit - priority'));
UPDATE exp_churches SET status_not_yet_visited = 0;
UPDATE exp_churches SET status_not_yet_visited = 1 WHERE note_id IN (SELECT note_id FROM note_tags WHERE tag_id = (SELECT id FROM tags WHERE title = 'status: not yet visited'));
